name: Muscle Authority
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 1
title: 'Muscle Authority Personal Training ,  Berne and Decatur Indiana'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d7ffc9'
    - '#006400'
    - '#31fc07'
    - '#1aac07'
  brandStrength: 1
  lightness: 0.73902
  saturation: 0.023649
  rhythmicContrast: 0.521115
purpose:
  - name: null
    item: null
    url: null
