analytics:
  google: UA-75059680-1
color:
  brandColors:
    - '#000000'
    - '#d7ffc9'
    - '#006400'
    - '#31fc07'
    - '#1aac07'
  brandStrength: 0
  lightness: 0.548142
  rhythmicContrast: 0.5
  saturation: 1
cta: {}
layout_spectrum: 0.75881
name: Muscle Authority
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.074324
