name: Muscle Authority
favicon: null
layout_spectrum: 0.75881
typography_spectrum: 0.30557
title: 'Muscle Authority "Make Your Body Great Again!"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75059680-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d7ffc9'
    - '#006400'
    - '#31fc07'
    - '#1aac07'
  brandStrength: 0
  lightness: 0.548142
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
