name: Muscle Authority
favicon: null
layout_spectrum: 0.15537
typography_spectrum: 0.345439
title: Muscle Authority Personal Training Fitness Consultations  Berne Indiana 46711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#676c66'
    - '#1a1b1a'
    - '#50524f'
    - '#363735'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.023649
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
